spring.application.name=devlink1

server.port=8080

spring.datasource.username=root
spring.datasource.password=whizthom
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/devlink

spring.thymeleaf.cache=false
spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false

# Show stack trace in error response
server.error.include-stacktrace=always

# Show error message
server.error.include-message=always

# Include binding/validation errors
server.error.include-binding-errors=always
